name: Security Audit

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read

env:
  # skip husky install on CI
  HUSKY: 0

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run security audit
        run: pnpm audit --audit-level=high
